class_name Constants extends Node

const MAX_BUBBLE_SCALE = 0.9999
const MAX_BUBBLE_DURATION = 25.
const BUBBLE_SCALE_SPEED_FACTOR = 0.5
const BUBBLE_MIN_SCALE = 0.2

const PLAIN_BUBBLE_RISE_ACCEL = 3.
const PLAIN_BUBBLE_RISE_MAX_SPEED = 2.
const PLAIN_BUBBLE_DRIFT_AMPLITUDE = 0.5
const PLAIN_BUBBLE_DRIFT_FREQUENCY = 1.5

const BUBBLE_WAND_COOLDOWN = 1.5
